### ISSUE TITLE
store.sync() causes endless loop

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hapi-couchdb-store#1]
To reproduce, open dev tools, have a look at network requests, then run this:

```js
store.add({})

.then(function () {
  return store.sync()
})

.then(function () {
  return store.sync()
})
```

I see endless calls in a loop. Not sure what is causing it, but pretty sure it's us :)

**Comment by HipsterBrown** [comment]
Got this error thrown when running that bit of code in the console. Should we be able to add an empty object to the store/PouchDB?

<img width="317" alt="screen shot 2015-08-08 at 1 00 30 pm" src="https://cloud.githubusercontent.com/assets/3051193/9151342/80061004-3dcd-11e5-9911-f85248d36fa3.png">

**Comment by HipsterBrown** [comment]
The loop is made up of just `pull` events and only occurs after calling `store.sync()` a 2nd time. I’m not completely familiar with how pouchdb replication with pouchdb-server works so I’m still investigating why this is the case.

**Comment by nolanlawson** [comment]
@HipsterBrown In my experience, "missing list of docs" is a slight red herring of an error message that CouchDB sends, usually when you try to access a URL path that's invalid (e.g. `/dbname/_foo`). Can you look in the Network tab and see which request is throwing the 400?

**Comment by nolanlawson** [comment]
Also I haven't looked at y'all's code yet, but are you `cancel()`ing syncs/replicates and waiting for the `'complete'` event before you restart them?

**Comment by HipsterBrown** [comment]
```js
var replication = this.sync(options.remote, {
      doc_ids: docsOrIds,
      include_docs: true
    })
 
    replication.catch(function () {
      // handled trough 'error' event
    })
 
    replication.on('complete', function () {
      defer.resolve(syncedObjects)
    })
    replication.on('error', defer.reject)
 
    replication.on('change', function (change) {
      syncedObjects = syncedObjects.concat(change.change.docs)
      console.warn('Changes!', change.direction, change.change)
 
      for (var i = 0; i < change.change.docs.length; i++) {
        state.emitter.emit(change.direction, change.change.docs[i])
   }
 })
```

This is what the sync module looks like at the moment (minus the `console.warn`). I'm not sure how the restarting or canceling works right now.

**Comment by nolanlawson** [comment]
OK, I've found the bug. It was subtle! It seems to be in the proxy that `pouchdb-hoodie-api` is using to proxy to pouchdb-server.

While debugging, I noticed that the `_changes` results coming back from CouchDB differed from those coming back from PouchDB Server. Even if you set `_changes?since=` to the `last_seq` (e.g. `_changes?since=6`), PouchDB Server would keep sending back the full list of docs, whereas CouchDB would correctly send an empty array.

![screenshot from 2015-08-23 19 39 59](https://cloud.githubusercontent.com/assets/283842/9430912/c3c0db24-49d2-11e5-8317-25900404084d.png)

But then I noticed that, if I tried sending that same `_changes` call *directly to localhost:5985* (i.e. directly to PouchDB Server) rather than through the localhost:3000 proxy, it would return the correct results!

![screenshot from 2015-08-23 20 03 12](https://cloud.githubusercontent.com/assets/283842/9430922/ded53748-49d2-11e5-9f80-1a1f73e9725c.png)

I'm guessing there is some configuration in the proxy you're using to tell it that `_changes?since=1` is different from `_changes?since=6`, because what seems to be happening right now is that they both end up with the same ETags. Here's a screenshot showing the difference - notice that PouchDB Server reports two different ETags whereas the proxy reports the same one:

![screenshot from 2015-08-23 20 12 53](https://cloud.githubusercontent.com/assets/283842/9430929/5d4c977e-49d3-11e5-87b1-a3d53dda7168.png)

Probably this has to do with the 304 tricking the proxy into thinking it can cache it with its own ETag. I've copied all the HAR responses here so you can analyze them:

* https://s3.amazonaws.com/nolanlawson/pouchdb/har/pouchdb-since-0.har
* https://s3.amazonaws.com/nolanlawson/pouchdb/har/pouchdb-since-1.har
* https://s3.amazonaws.com/nolanlawson/pouchdb/har/proxy-since-0.har
* https://s3.amazonaws.com/nolanlawson/pouchdb/har/proxy-since-1.har

**Comment by HipsterBrown** [comment]
Thanks for the awesome & thorough write-up @nolanlawson. I'll start looking into the `pouchdb-hoodie-api` source.

**Comment by gr2m** [comment]
Wow, thanks a lot @nolanlawson

**Comment by Charlotteis** [comment]
nice one @nolanlawson, thanks!

**Comment by nolanlawson** [comment]
No prob, also for the record I played around with the Hapi proxy a bit in `couchdb-proxy.js`, but couldn't figure out how to disable caching. :/ I'm sure it's some setting we need to tinker with, else it's a bug in Hapi itself causing it to apply the same ETag.

**Comment by HipsterBrown** [comment]
I reproduced the bug locally and then changed the `store` to use the `pouchdb-server` port as the `remoteBaseUrl` to run the original script correctly. I saved a [log](https://www.dropbox.com/s/oanbwezmj0nib4w/hapi-couchdb-store-loop-bug.log?dl=0) and [har](https://www.dropbox.com/s/adl2tccmhrx4dkr/hap-couchdb-store-loop-bug.har?dl=0) after running all that, for anyone who wants to check them out while debugging.
